name: school_app
description: "BELTEL IS"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  lottie: ^3.1.0
  google_generative_ai: ^0.4.4
  flutter_localization: ^0.3.3
  webview_flutter: ^4.10.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.0
  share_plus: ^10.1.0
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/tottie/robot.json
    - assets/tottie/user_robot.json
  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700