name: school_app
description: "NANJING UNIVERSITY"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  intl: ^0.20.2

  # UI & Animations
  marquee: ^2.2.3
  lottie: ^3.1.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^8.0.0
  fl_chart: ^1.1.1
  mobile_scanner: ^7.1.4
  shimmer: ^3.0.0
  audioplayers: ^6.1.0
  flutter_local_notifications: ^20.0.0
  qr_flutter: ^4.0.0

  # API / Storage
  flutter_secure_storage: ^10.0.0
  provider: ^6.1.1
  shared_preferences: ^2.3.5

  # Video & YouTube
  youtube_player_flutter: ^9.1.3
  video_player: ^2.9.1

  # Web & URL
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  share_plus: ^12.0.1
  image_picker: ^1.0.7

  # AI & Localization
  google_generative_ai: ^0.4.4
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
    - assets/image/background_login.png
    - assets/tottie/
    - assets/fonts/

  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700
