name: school_app
description: "NANJING UNIVERSITY"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  marquee: ^2.2.3
  lottie: ^3.1.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Video & YouTube
  youtube_player_flutter: ^9.1.3
  video_player: ^2.9.1

  # Web & URL
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  share_plus: ^12.0.1

  # State & Storage
  provider: ^6.1.1
  shared_preferences: ^2.3.5

  # AI & Localization
  google_generative_ai: ^0.4.4
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Fix conflicts
dependency_overrides:
  flutter_inappwebview: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
    - assets/image/       # Include all images in this folder
    - assets/tottie/      # Ensure this folder exists
    - assets/fonts/       # You can include entire fonts folder if needed

  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700
fonts:
  - family: MaoTi
    fonts:
      - asset: assets/font/FZMaoti.ttf